languageCode = "en-us"
title = "./sigterm.sh"
# Enable comments by entering your Disqus shortname
disqusShortname = "codegeeksh"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-11073510-1"
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "mainroad"
baseurl = "/"
PygmentsCodeFences = true

[permalinks]
    post = "/:year/:month/:day/:slug"

[Author]
    name = "Gregory Armer"
    bio = "Sometimes I just want to give it all up and become a handsome billionaire."
    avatar = "greg.png"

[params]
    location = "New York, NY"
    subtitle = "The raddest of all the kill signals."
    copyright  = "Gregory Armer. All rights reserved."

    # Format dates with Go's time formatting
    date_format = "Jan 02, 2006"

    # Add custom assets with their paths relative to the static folder
    custom_css = ["custom.css"]
    custom_js  = []

    opengraph = true # Enable OpenGraph if true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true # Show authorbox at bottom of pages if true
    post_navigation = true # Show post navigation at bottom of pages if true
    postSections = ["post"] # the section pages to show on home page and the "Recent articles" widget
    #postSections = ["blog", "news"] # alternative that shows more than one section's pages

[[menu.main]]
    name = "Blog"
    weight = -110
    url = "/"
[[menu.main]]
    name = "Code"
    weight = -100
    url = "/code/"
[[menu.main]]
    name = "dn42 peering"
    weight = -90
    url = "/dn42-peering/"
[[menu.main]]
    name = "audiophilia"
    weight = -80
    url = "/audiophilia/"
[[menu.main]]
    name = "paragliding"
    weight = -70
    url = "/paragliding/"
[[menu.main]]
    name = "About"
    weight = -60
    url = "/about/"

# Enable and disable widgets for the right sidebar
[params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 7 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)

    # Enable "Social" widget, if any of "social_*" set a value
    #social_facebook = "username"
    social_twitter = "gregarmer"
    #social_linkedin = "username"
    social_github = "gregarmer"
    #social_email = "greg@sigterm.sh"
    #social_google_plus = "gregoryarmer"
